# Generated by Django 3.0.2 on 2020-02-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emailId', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500000)),
            ],
        ),
    ]
